[project]
name = "intake"
version = "0.0.1"

[project.scripts]
intake = "intake.cli:main"

[tool.setuptools]
packages = ["intake", "intake.templates"]

[tool.setuptools.package-data]
"intake.templates" = ["*.jinja2"]
